Fourth milestone
bren2102/Calculator-react pull request #4
Opened 2020-07-21 20:37 UTC by bren2102

Kindly request a code review for the fourth milestone of this calculator project.

1. Logic folder with calculate.js and  operate.js created
2. calculate.js module implemented
- Contains one method: calculate
- Calculate method accepts data object and buttonName
- The data object contains three properties: total, next, and operation.
- This method uses the buttonName argument to mutate the calculator’s data object and return its modified version.
3. operate.js module implement
- Import big.js module
- Implement one function: operate
- The operate function accepts numberOne, numberTwo, and operation as arguments.
- Uses the value of the operation argument
- buttonName in calculate.js uses total properties
4. calculate.js imported to the App component

2020-07-22 06:34 UTC, Oghenebrume50 requested changes
### CHANGES REQUIRED

Hi @bren2102 awesome job, this is well written, however, I have pointed out some few changes, please look into those and when you are done request for another review :slightly_smiling_face: 

Please make changes and **request for another review**


**RAPHAEL NORIODE** :mask: stay_safe

2020-07-22 06:34 UTC, Oghenebrume50 commented on src/logic/operate.js
> +        return ((nOne.div(100)).times(nTwo)).toString();
I think you need to turn the number into a percentile here and the only way to do that is to divide by 100, no need multiplying with the second number. percentage works with just one input 
![see](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone4/performOperate.png)

2020-07-22 06:34 UTC, Oghenebrume50 commented on src/logic/operate.js
> +      if (nOne !== 0 && nTwo !== 0) {
0 / num is well known in mathematics as zero, the only thing you need to check is the other way around so num / 0 this is when we have a problem

2020-07-23 06:33 UTC, suretrust approved these changes
Hi @bren2102, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍 

_Good luck with your future milestones and happy coding!_ 🎉

2020-07-23 14:05 UTC, merged